# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Mon Jun 20 23:36:37 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.inputFileGroup = QtWidgets.QGroupBox(self.widget)
        self.inputFileGroup.setObjectName("inputFileGroup")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.inputFileGroup)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.inputCsvLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.inputCsvLineEdit.setReadOnly(True)
        self.inputCsvLineEdit.setObjectName("inputCsvLineEdit")
        self.horizontalLayout_10.addWidget(self.inputCsvLineEdit)
        self.chooseInputFileButton = QtWidgets.QToolButton(self.inputFileGroup)
        self.chooseInputFileButton.setObjectName("chooseInputFileButton")
        self.horizontalLayout_10.addWidget(self.chooseInputFileButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dateColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.dateColumnLabel.setObjectName("dateColumnLabel")
        self.verticalLayout_7.addWidget(self.dateColumnLabel)
        self.dateColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.dateColumnLineEdit.setObjectName("dateColumnLineEdit")
        self.verticalLayout_7.addWidget(self.dateColumnLineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lengthColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.lengthColumnLabel.setObjectName("lengthColumnLabel")
        self.verticalLayout_8.addWidget(self.lengthColumnLabel)
        self.lengthColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.lengthColumnLineEdit.setObjectName("lengthColumnLineEdit")
        self.verticalLayout_8.addWidget(self.lengthColumnLineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.quantityColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.quantityColumnLabel.setObjectName("quantityColumnLabel")
        self.verticalLayout_9.addWidget(self.quantityColumnLabel)
        self.quantityColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.quantityColumnLineEdit.setObjectName("quantityColumnLineEdit")
        self.verticalLayout_9.addWidget(self.quantityColumnLineEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addWidget(self.inputFileGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.detailedSimGroup = QtWidgets.QGroupBox(self.widget1)
        self.detailedSimGroup.setEnabled(False)
        self.detailedSimGroup.setObjectName("detailedSimGroup")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.detailedSimGroup)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.supplierBarLengthLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.supplierBarLengthLabel.setObjectName("supplierBarLengthLabel")
        self.horizontalLayout_12.addWidget(self.supplierBarLengthLabel)
        self.supplierBarLengthSpinBox = QtWidgets.QSpinBox(self.detailedSimGroup)
        self.supplierBarLengthSpinBox.setMaximum(99999)
        self.supplierBarLengthSpinBox.setProperty("value", 7000)
        self.supplierBarLengthSpinBox.setObjectName("supplierBarLengthSpinBox")
        self.horizontalLayout_12.addWidget(self.supplierBarLengthSpinBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.toTrashLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.toTrashLabel.setObjectName("toTrashLabel")
        self.horizontalLayout_13.addWidget(self.toTrashLabel)
        self.toTrashSpinBox = QtWidgets.QSpinBox(self.detailedSimGroup)
        self.toTrashSpinBox.setMaximum(99999)
        self.toTrashSpinBox.setProperty("value", 1200)
        self.toTrashSpinBox.setObjectName("toTrashSpinBox")
        self.horizontalLayout_13.addWidget(self.toTrashSpinBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.detailedOutDirLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.detailedOutDirLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.detailedOutDirLabel.setObjectName("detailedOutDirLabel")
        self.verticalLayout_11.addWidget(self.detailedOutDirLabel)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.detailedDirLine = QtWidgets.QLineEdit(self.detailedSimGroup)
        self.detailedDirLine.setReadOnly(True)
        self.detailedDirLine.setObjectName("detailedDirLine")
        self.horizontalLayout_14.addWidget(self.detailedDirLine)
        self.chooseDetailedOutDirButton = QtWidgets.QToolButton(self.detailedSimGroup)
        self.chooseDetailedOutDirButton.setObjectName("chooseDetailedOutDirButton")
        self.horizontalLayout_14.addWidget(self.chooseDetailedOutDirButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_19.addLayout(self.verticalLayout_12)
        self.verticalLayout_16.addWidget(self.detailedSimGroup)
        self.optimizationGroup = QtWidgets.QGroupBox(self.widget1)
        self.optimizationGroup.setObjectName("optimizationGroup")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.optimizationGroup)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputDirLabel = QtWidgets.QLabel(self.optimizationGroup)
        self.outputDirLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.outputDirLabel.setObjectName("outputDirLabel")
        self.verticalLayout.addWidget(self.outputDirLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputDirLineEdit = QtWidgets.QLineEdit(self.optimizationGroup)
        self.outputDirLineEdit.setReadOnly(True)
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.horizontalLayout.addWidget(self.outputDirLineEdit)
        self.chooseOutputDirButton = QtWidgets.QToolButton(self.optimizationGroup)
        self.chooseOutputDirButton.setObjectName("chooseOutputDirButton")
        self.horizontalLayout.addWidget(self.chooseOutputDirButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.optimSupplierBarConfigGroup = QtWidgets.QGroupBox(self.optimizationGroup)
        self.optimSupplierBarConfigGroup.setMinimumSize(QtCore.QSize(150, 120))
        self.optimSupplierBarConfigGroup.setObjectName("optimSupplierBarConfigGroup")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.optimSupplierBarConfigGroup)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.supplierBarLengthMinLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMinLabel.setObjectName("supplierBarLengthMinLabel")
        self.horizontalLayout_3.addWidget(self.supplierBarLengthMinLabel)
        self.supplierBarLengthMinSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMinSpinBox.setAcceptDrops(False)
        self.supplierBarLengthMinSpinBox.setMaximum(99999)
        self.supplierBarLengthMinSpinBox.setProperty("value", 0)
        self.supplierBarLengthMinSpinBox.setObjectName("supplierBarLengthMinSpinBox")
        self.horizontalLayout_3.addWidget(self.supplierBarLengthMinSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.supplierBarLengthMaxLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMaxLabel.setObjectName("supplierBarLengthMaxLabel")
        self.horizontalLayout_4.addWidget(self.supplierBarLengthMaxLabel)
        self.supplierBarLengthMaxSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMaxSpinBox.setMaximum(99999)
        self.supplierBarLengthMaxSpinBox.setProperty("value", 0)
        self.supplierBarLengthMaxSpinBox.setObjectName("supplierBarLengthMaxSpinBox")
        self.horizontalLayout_4.addWidget(self.supplierBarLengthMaxSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.supplierBarLengthStepLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthStepLabel.setObjectName("supplierBarLengthStepLabel")
        self.horizontalLayout_5.addWidget(self.supplierBarLengthStepLabel)
        self.supplierBarLengthStepSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthStepSpinBox.setMaximum(99999)
        self.supplierBarLengthStepSpinBox.setProperty("value", 0)
        self.supplierBarLengthStepSpinBox.setObjectName("supplierBarLengthStepSpinBox")
        self.horizontalLayout_5.addWidget(self.supplierBarLengthStepSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_22.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.optimSupplierBarConfigGroup)
        self.optimTrashConfigGroup = QtWidgets.QGroupBox(self.optimizationGroup)
        self.optimTrashConfigGroup.setMinimumSize(QtCore.QSize(150, 120))
        self.optimTrashConfigGroup.setObjectName("optimTrashConfigGroup")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.optimTrashConfigGroup)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toTrashMinLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashMinLabel.setObjectName("toTrashMinLabel")
        self.horizontalLayout_6.addWidget(self.toTrashMinLabel)
        self.toTrashMinSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashMinSpinBox.setMaximum(99999)
        self.toTrashMinSpinBox.setProperty("value", 0)
        self.toTrashMinSpinBox.setObjectName("toTrashMinSpinBox")
        self.horizontalLayout_6.addWidget(self.toTrashMinSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toTrashMaxLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashMaxLabel.setObjectName("toTrashMaxLabel")
        self.horizontalLayout_7.addWidget(self.toTrashMaxLabel)
        self.toTrashMaxSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashMaxSpinBox.setMaximum(99999)
        self.toTrashMaxSpinBox.setProperty("value", 0)
        self.toTrashMaxSpinBox.setObjectName("toTrashMaxSpinBox")
        self.horizontalLayout_7.addWidget(self.toTrashMaxSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toTrashStepLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashStepLabel.setObjectName("toTrashStepLabel")
        self.horizontalLayout_8.addWidget(self.toTrashStepLabel)
        self.toTrashStepSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashStepSpinBox.setMaximum(99999)
        self.toTrashStepSpinBox.setProperty("value", 0)
        self.toTrashStepSpinBox.setObjectName("toTrashStepSpinBox")
        self.horizontalLayout_8.addWidget(self.toTrashStepSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_21.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.optimTrashConfigGroup)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_20.addLayout(self.verticalLayout_2)
        self.verticalLayout_16.addWidget(self.optimizationGroup)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.simulationGroup = QtWidgets.QGroupBox(self.widget2)
        self.simulationGroup.setObjectName("simulationGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.simulationGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.optimizationRadioButton = QtWidgets.QRadioButton(self.simulationGroup)
        self.optimizationRadioButton.setChecked(True)
        self.optimizationRadioButton.setObjectName("optimizationRadioButton")
        self.verticalLayout_5.addWidget(self.optimizationRadioButton)
        self.detailedSimRadioButton = QtWidgets.QRadioButton(self.simulationGroup)
        self.detailedSimRadioButton.setObjectName("detailedSimRadioButton")
        self.verticalLayout_5.addWidget(self.detailedSimRadioButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_15.addWidget(self.simulationGroup)
        self.commandsGroup = QtWidgets.QGroupBox(self.widget2)
        self.commandsGroup.setObjectName("commandsGroup")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.commandsGroup)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.launchButton = QtWidgets.QPushButton(self.commandsGroup)
        self.launchButton.setObjectName("launchButton")
        self.verticalLayout_13.addWidget(self.launchButton)
        self.openLogButton = QtWidgets.QPushButton(self.commandsGroup)
        self.openLogButton.setObjectName("openLogButton")
        self.verticalLayout_13.addWidget(self.openLogButton)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_15.addWidget(self.commandsGroup)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.consoleGroup = QtWidgets.QGroupBox(self.splitter_2)
        self.consoleGroup.setMinimumSize(QtCore.QSize(0, 150))
        self.consoleGroup.setObjectName("consoleGroup")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.consoleGroup)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.console = QtWidgets.QPlainTextEdit(self.consoleGroup)
        self.console.setObjectName("console")
        self.horizontalLayout_18.addWidget(self.console)
        self.horizontalLayout_9.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openSettingsAction = QtWidgets.QAction(MainWindow)
        self.openSettingsAction.setObjectName("openSettingsAction")
        self.saveSettingsAction = QtWidgets.QAction(MainWindow)
        self.saveSettingsAction.setObjectName("saveSettingsAction")
        self.fileMenu.addAction(self.openSettingsAction)
        self.fileMenu.addAction(self.saveSettingsAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.detailedSimRadioButton.toggled['bool'].connect(self.detailedSimGroup.setEnabled)
        self.optimizationRadioButton.toggled['bool'].connect(self.optimizationGroup.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BarSupplyOptimizer"))
        self.inputFileGroup.setTitle(_translate("MainWindow", "Fichier d\'entrée"))
        self.chooseInputFileButton.setText(_translate("MainWindow", "..."))
        self.dateColumnLabel.setText(_translate("MainWindow", "Nom colonne date"))
        self.lengthColumnLabel.setText(_translate("MainWindow", "Nom colonne longueur"))
        self.quantityColumnLabel.setText(_translate("MainWindow", "Nom colonne quantité"))
        self.detailedSimGroup.setTitle(_translate("MainWindow", "Simulation Détaillée"))
        self.supplierBarLengthLabel.setText(_translate("MainWindow", "Taille barres fournisseur"))
        self.toTrashLabel.setText(_translate("MainWindow", "Limite poubelle"))
        self.detailedOutDirLabel.setText(_translate("MainWindow", "Répertoire de sortie"))
        self.chooseDetailedOutDirButton.setText(_translate("MainWindow", "..."))
        self.optimizationGroup.setTitle(_translate("MainWindow", "Mode Optimisation"))
        self.outputDirLabel.setText(_translate("MainWindow", "Répertoire de sortie"))
        self.chooseOutputDirButton.setText(_translate("MainWindow", "..."))
        self.optimSupplierBarConfigGroup.setTitle(_translate("MainWindow", "Taille barre fournisseur"))
        self.supplierBarLengthMinLabel.setText(_translate("MainWindow", "minimum"))
        self.supplierBarLengthMaxLabel.setText(_translate("MainWindow", "maximum"))
        self.supplierBarLengthStepLabel.setText(_translate("MainWindow", "pas"))
        self.optimTrashConfigGroup.setTitle(_translate("MainWindow", "Limite poubelle"))
        self.toTrashMinLabel.setText(_translate("MainWindow", "minimum"))
        self.toTrashMaxLabel.setText(_translate("MainWindow", "maximum"))
        self.toTrashStepLabel.setText(_translate("MainWindow", "pas"))
        self.simulationGroup.setTitle(_translate("MainWindow", "Simulation"))
        self.optimizationRadioButton.setText(_translate("MainWindow", "Optimisation"))
        self.detailedSimRadioButton.setText(_translate("MainWindow", "Détaillée"))
        self.commandsGroup.setTitle(_translate("MainWindow", "Simulation"))
        self.launchButton.setText(_translate("MainWindow", "Lancer"))
        self.openLogButton.setText(_translate("MainWindow", "Ouvrir fichier simulation"))
        self.consoleGroup.setTitle(_translate("MainWindow", "Console"))
        self.fileMenu.setTitle(_translate("MainWindow", "Fichier"))
        self.openSettingsAction.setText(_translate("MainWindow", "Ouvrir configuration..."))
        self.openSettingsAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveSettingsAction.setText(_translate("MainWindow", "Sauvegarder configuration..."))
        self.saveSettingsAction.setShortcut(_translate("MainWindow", "Ctrl+S"))

