# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Sun Jun 19 18:51:18 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputFileGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.inputFileGroup.setGeometry(QtCore.QRect(30, 20, 201, 211))
        self.inputFileGroup.setObjectName("inputFileGroup")
        self.chooseInputFileButton = QtWidgets.QToolButton(self.inputFileGroup)
        self.chooseInputFileButton.setGeometry(QtCore.QRect(170, 20, 25, 19))
        self.chooseInputFileButton.setObjectName("chooseInputFileButton")
        self.inputCsvLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.inputCsvLineEdit.setGeometry(QtCore.QRect(10, 20, 151, 20))
        self.inputCsvLineEdit.setReadOnly(True)
        self.inputCsvLineEdit.setObjectName("inputCsvLineEdit")
        self.dateColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.dateColumnLabel.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.dateColumnLabel.setObjectName("dateColumnLabel")
        self.dateColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.dateColumnLineEdit.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.dateColumnLineEdit.setObjectName("dateColumnLineEdit")
        self.lengthColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.lengthColumnLineEdit.setGeometry(QtCore.QRect(10, 120, 181, 20))
        self.lengthColumnLineEdit.setObjectName("lengthColumnLineEdit")
        self.lengthColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.lengthColumnLabel.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.lengthColumnLabel.setObjectName("lengthColumnLabel")
        self.quantityColumnLabel = QtWidgets.QLabel(self.inputFileGroup)
        self.quantityColumnLabel.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.quantityColumnLabel.setObjectName("quantityColumnLabel")
        self.quantityColumnLineEdit = QtWidgets.QLineEdit(self.inputFileGroup)
        self.quantityColumnLineEdit.setGeometry(QtCore.QRect(10, 170, 181, 20))
        self.quantityColumnLineEdit.setObjectName("quantityColumnLineEdit")
        self.simulationGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.simulationGroup.setGeometry(QtCore.QRect(30, 240, 191, 71))
        self.simulationGroup.setObjectName("simulationGroup")
        self.detailedSimRadioButton = QtWidgets.QRadioButton(self.simulationGroup)
        self.detailedSimRadioButton.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.detailedSimRadioButton.setObjectName("detailedSimRadioButton")
        self.optimizationRadioButton = QtWidgets.QRadioButton(self.simulationGroup)
        self.optimizationRadioButton.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.optimizationRadioButton.setChecked(True)
        self.optimizationRadioButton.setObjectName("optimizationRadioButton")
        self.detailedSimGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.detailedSimGroup.setEnabled(False)
        self.detailedSimGroup.setGeometry(QtCore.QRect(490, 30, 231, 161))
        self.detailedSimGroup.setObjectName("detailedSimGroup")
        self.supplierBarLengthLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.supplierBarLengthLabel.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.supplierBarLengthLabel.setObjectName("supplierBarLengthLabel")
        self.supplierBarLengthSpinBox = QtWidgets.QSpinBox(self.detailedSimGroup)
        self.supplierBarLengthSpinBox.setGeometry(QtCore.QRect(140, 30, 71, 22))
        self.supplierBarLengthSpinBox.setMaximum(99999)
        self.supplierBarLengthSpinBox.setProperty("value", 7000)
        self.supplierBarLengthSpinBox.setObjectName("supplierBarLengthSpinBox")
        self.toTrashLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.toTrashLabel.setGeometry(QtCore.QRect(20, 70, 121, 16))
        self.toTrashLabel.setObjectName("toTrashLabel")
        self.toTrashSpinBox = QtWidgets.QSpinBox(self.detailedSimGroup)
        self.toTrashSpinBox.setGeometry(QtCore.QRect(140, 70, 71, 22))
        self.toTrashSpinBox.setMaximum(99999)
        self.toTrashSpinBox.setProperty("value", 1200)
        self.toTrashSpinBox.setObjectName("toTrashSpinBox")
        self.chooseDetailedOutDirButton = QtWidgets.QToolButton(self.detailedSimGroup)
        self.chooseDetailedOutDirButton.setGeometry(QtCore.QRect(180, 120, 25, 19))
        self.chooseDetailedOutDirButton.setObjectName("chooseDetailedOutDirButton")
        self.detailedDirLine = QtWidgets.QLineEdit(self.detailedSimGroup)
        self.detailedDirLine.setGeometry(QtCore.QRect(20, 120, 113, 20))
        self.detailedDirLine.setReadOnly(True)
        self.detailedDirLine.setObjectName("detailedDirLine")
        self.detailedOutDirLabel = QtWidgets.QLabel(self.detailedSimGroup)
        self.detailedOutDirLabel.setGeometry(QtCore.QRect(20, 100, 121, 16))
        self.detailedOutDirLabel.setObjectName("detailedOutDirLabel")
        self.optimizationGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.optimizationGroup.setGeometry(QtCore.QRect(260, 20, 211, 381))
        self.optimizationGroup.setObjectName("optimizationGroup")
        self.optimSupplierBarConfigGroup = QtWidgets.QGroupBox(self.optimizationGroup)
        self.optimSupplierBarConfigGroup.setGeometry(QtCore.QRect(10, 20, 181, 141))
        self.optimSupplierBarConfigGroup.setObjectName("optimSupplierBarConfigGroup")
        self.supplierBarLengthMaxSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMaxSpinBox.setGeometry(QtCore.QRect(80, 60, 71, 22))
        self.supplierBarLengthMaxSpinBox.setMaximum(99999)
        self.supplierBarLengthMaxSpinBox.setProperty("value", 0)
        self.supplierBarLengthMaxSpinBox.setObjectName("supplierBarLengthMaxSpinBox")
        self.supplierBarLengthMinSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMinSpinBox.setGeometry(QtCore.QRect(80, 20, 71, 22))
        self.supplierBarLengthMinSpinBox.setAcceptDrops(False)
        self.supplierBarLengthMinSpinBox.setMaximum(99999)
        self.supplierBarLengthMinSpinBox.setProperty("value", 0)
        self.supplierBarLengthMinSpinBox.setObjectName("supplierBarLengthMinSpinBox")
        self.supplierBarLengthStepSpinBox = QtWidgets.QSpinBox(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthStepSpinBox.setGeometry(QtCore.QRect(80, 100, 71, 22))
        self.supplierBarLengthStepSpinBox.setMaximum(99999)
        self.supplierBarLengthStepSpinBox.setProperty("value", 0)
        self.supplierBarLengthStepSpinBox.setObjectName("supplierBarLengthStepSpinBox")
        self.supplierBarLengthMinLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMinLabel.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.supplierBarLengthMinLabel.setObjectName("supplierBarLengthMinLabel")
        self.supplierBarLengthMaxLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthMaxLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.supplierBarLengthMaxLabel.setObjectName("supplierBarLengthMaxLabel")
        self.supplierBarLengthStepLabel = QtWidgets.QLabel(self.optimSupplierBarConfigGroup)
        self.supplierBarLengthStepLabel.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.supplierBarLengthStepLabel.setObjectName("supplierBarLengthStepLabel")
        self.optimTrashConfigGroup = QtWidgets.QGroupBox(self.optimizationGroup)
        self.optimTrashConfigGroup.setGeometry(QtCore.QRect(10, 170, 181, 141))
        self.optimTrashConfigGroup.setObjectName("optimTrashConfigGroup")
        self.toTrashMaxSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashMaxSpinBox.setGeometry(QtCore.QRect(80, 60, 71, 22))
        self.toTrashMaxSpinBox.setMaximum(99999)
        self.toTrashMaxSpinBox.setProperty("value", 0)
        self.toTrashMaxSpinBox.setObjectName("toTrashMaxSpinBox")
        self.toTrashMinSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashMinSpinBox.setGeometry(QtCore.QRect(80, 20, 71, 22))
        self.toTrashMinSpinBox.setMaximum(99999)
        self.toTrashMinSpinBox.setProperty("value", 0)
        self.toTrashMinSpinBox.setObjectName("toTrashMinSpinBox")
        self.toTrashStepSpinBox = QtWidgets.QSpinBox(self.optimTrashConfigGroup)
        self.toTrashStepSpinBox.setGeometry(QtCore.QRect(80, 100, 71, 22))
        self.toTrashStepSpinBox.setMaximum(99999)
        self.toTrashStepSpinBox.setProperty("value", 0)
        self.toTrashStepSpinBox.setObjectName("toTrashStepSpinBox")
        self.toTrashMinLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashMinLabel.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.toTrashMinLabel.setObjectName("toTrashMinLabel")
        self.toTrashMaxLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashMaxLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.toTrashMaxLabel.setObjectName("toTrashMaxLabel")
        self.toTrashStepLabel = QtWidgets.QLabel(self.optimTrashConfigGroup)
        self.toTrashStepLabel.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.toTrashStepLabel.setObjectName("toTrashStepLabel")
        self.chooseOutputDirButton = QtWidgets.QToolButton(self.optimizationGroup)
        self.chooseOutputDirButton.setGeometry(QtCore.QRect(170, 340, 25, 19))
        self.chooseOutputDirButton.setObjectName("chooseOutputDirButton")
        self.outputDirLabel = QtWidgets.QLabel(self.optimizationGroup)
        self.outputDirLabel.setGeometry(QtCore.QRect(10, 320, 121, 16))
        self.outputDirLabel.setObjectName("outputDirLabel")
        self.outputDirLineEdit = QtWidgets.QLineEdit(self.optimizationGroup)
        self.outputDirLineEdit.setGeometry(QtCore.QRect(10, 340, 113, 20))
        self.outputDirLineEdit.setReadOnly(True)
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.commandsGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.commandsGroup.setGeometry(QtCore.QRect(490, 200, 181, 101))
        self.commandsGroup.setObjectName("commandsGroup")
        self.launchButton = QtWidgets.QPushButton(self.commandsGroup)
        self.launchButton.setGeometry(QtCore.QRect(20, 20, 141, 23))
        self.launchButton.setObjectName("launchButton")
        self.openLogButton = QtWidgets.QPushButton(self.commandsGroup)
        self.openLogButton.setGeometry(QtCore.QRect(20, 50, 141, 23))
        self.openLogButton.setObjectName("openLogButton")
        self.consoleGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.consoleGroup.setGeometry(QtCore.QRect(20, 420, 721, 241))
        self.consoleGroup.setObjectName("consoleGroup")
        self.console = QtWidgets.QPlainTextEdit(self.consoleGroup)
        self.console.setGeometry(QtCore.QRect(0, 20, 721, 221))
        self.console.setObjectName("console")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openSettingsAction = QtWidgets.QAction(MainWindow)
        self.openSettingsAction.setObjectName("openSettingsAction")
        self.saveSettingsAction = QtWidgets.QAction(MainWindow)
        self.saveSettingsAction.setObjectName("saveSettingsAction")
        self.fileMenu.addAction(self.openSettingsAction)
        self.fileMenu.addAction(self.saveSettingsAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.detailedSimRadioButton.toggled['bool'].connect(self.detailedSimGroup.setEnabled)
        self.optimizationRadioButton.toggled['bool'].connect(self.optimizationGroup.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BarSupplyOptimizer"))
        self.inputFileGroup.setTitle(_translate("MainWindow", "Fichier d\'entrée"))
        self.chooseInputFileButton.setText(_translate("MainWindow", "..."))
        self.dateColumnLabel.setText(_translate("MainWindow", "Nom colonne date"))
        self.lengthColumnLabel.setText(_translate("MainWindow", "Nom colonne longueur"))
        self.quantityColumnLabel.setText(_translate("MainWindow", "Nom colonne quantité"))
        self.simulationGroup.setTitle(_translate("MainWindow", "Simulation"))
        self.detailedSimRadioButton.setText(_translate("MainWindow", "Détaillée"))
        self.optimizationRadioButton.setText(_translate("MainWindow", "Optimisation"))
        self.detailedSimGroup.setTitle(_translate("MainWindow", "Simulation Détaillée"))
        self.supplierBarLengthLabel.setText(_translate("MainWindow", "Taille barres fournisseur"))
        self.toTrashLabel.setText(_translate("MainWindow", "Limite poubelle"))
        self.chooseDetailedOutDirButton.setText(_translate("MainWindow", "..."))
        self.detailedOutDirLabel.setText(_translate("MainWindow", "Répertoire de sortie"))
        self.optimizationGroup.setTitle(_translate("MainWindow", "Mode Optimisation"))
        self.optimSupplierBarConfigGroup.setTitle(_translate("MainWindow", "Taille barre fournisseur"))
        self.supplierBarLengthMinLabel.setText(_translate("MainWindow", "minimum"))
        self.supplierBarLengthMaxLabel.setText(_translate("MainWindow", "maximum"))
        self.supplierBarLengthStepLabel.setText(_translate("MainWindow", "pas"))
        self.optimTrashConfigGroup.setTitle(_translate("MainWindow", "Limite poubelle"))
        self.toTrashMinLabel.setText(_translate("MainWindow", "minimum"))
        self.toTrashMaxLabel.setText(_translate("MainWindow", "maximum"))
        self.toTrashStepLabel.setText(_translate("MainWindow", "pas"))
        self.chooseOutputDirButton.setText(_translate("MainWindow", "..."))
        self.outputDirLabel.setText(_translate("MainWindow", "Répertoire de sortie"))
        self.commandsGroup.setTitle(_translate("MainWindow", "Simulation"))
        self.launchButton.setText(_translate("MainWindow", "Lancer"))
        self.openLogButton.setText(_translate("MainWindow", "Ouvrir fichier simulation"))
        self.consoleGroup.setTitle(_translate("MainWindow", "Console"))
        self.fileMenu.setTitle(_translate("MainWindow", "Fichier"))
        self.openSettingsAction.setText(_translate("MainWindow", "Ouvrir configuration..."))
        self.openSettingsAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveSettingsAction.setText(_translate("MainWindow", "Sauvegarder configuration..."))
        self.saveSettingsAction.setShortcut(_translate("MainWindow", "Ctrl+S"))

